name: ci

permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  contents: write

on:
  pull_request:
  push:
    branches: [main, rewrite]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: make docker-test
