name: ci

permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  contents: write

on:
  pull_request:
  push:
    branches: [main, rewrite]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make test-docker
    
  build:
    runs-on: ubuntu-latest
    needs: ["test"]
    steps:
        - uses: actions/checkout@v4
        - run: make build-docker
